<?php

namespace DesignPatterns\Structural\Decorator;

class RedPaintingDecorator extends PaintingDecorator
{
  const MY_COLOR = 'Red';

  public function paint(Car $car): bool
  {
    $car->setColor(self::MY_COLOR);
    return parent::paint($car); // TODO: Change the autogenerated stub
  }
}